version: 2
jobs:
  build:
#    docker:
#      - image: circleci/openjdk:11-jdk

    # Uses a "medium" sized machine - maybe increase this to "large" if you pay for CircleCI
    resource_class: medium
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx6400m
    machine:
      image: ubuntu-2004:202008-01
    steps:
      # Checkout the source code
      # ########################
      - checkout

#      # Restore any files we may have cached
#      # ########################
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "pom.xml" }}
#            # fallback to using the latest cache if no exact match is found
#            - v1-dependencies-
#
#      # Download maven dependencies so that we can cache them
#      # ########################
#      - run:
#          name: Download Dependencies
#          command: mvn dependency:go-offline
#      # Cache the maven dependencies
#      - save_cache:
#          paths:
#            - ~/.m2
#          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Standard maven build and test phases - does not perform a native build (or verify)
      # ########################
      - run:
          name: Build (Standard)
          command: mvn clean install -DskipTests
      - run:
          name: Verify (Standard)
          command: mvn test
