version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  maven/test:
    docker:
      - image: circleci/openjdk:11-jdk-node
    steps:
      - run:
          name: Install Dependencies
          dependencies:
            override:
              - mvn install -DskipTests
      - run:
          name: Run Tests
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
workflows:
  maven_test:
    jobs:
      - maven/test
  version: 2
