version: 2
jobs:
  build:
    ## Use preconfigured circleci image that has JDK 11 by default See https://discuss.circleci.com/t/early-preview-new-ubuntu-20-04-linux-machine-executor-image/37281
    ## has JDK 11, docker and maven
    machine:
      image: ubuntu-2004:202008-01
    # Uses a "medium" sized machine (this is the default) - maybe increase this to "large" if you pay for CircleCI
    resource_class: medium
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx6400m
    steps:
      # Checkout the source code
      - checkout
      # Build the project
      # This will cache the multi module jars in the local m2 repo and build the docker images
      - run:
          name: Build
          command: mvn clean install -DskipTests
      - run:
          name: Test
          command: mvn test
